# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy dependency definitions
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running scripts (to skip prepare if needed)
RUN pnpm install --ignore-scripts

# Copy the rest of the code
COPY . .

# Build the project
RUN pnpm run build

# Expose a port if your MCP server listens on one (optional)
# EXPOSE 3000

# Run the MCP server
CMD ["node", "dist/index.js"]
