# Make sure the EventCatalog MCP server can build and test OK
name: Verify Build and Test

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Verify Build and Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Installation
        run: pnpm i
      - name: Test
        run: pnpm run test
      - name: Build package
        run: pnpm run build